### PR TITLE
Add configuration variable to set the dust threshold for change amounts.

### LINKED ISSUE #208: Yield generator shouldnt create dust
It's unfortunate that the yield generator can create dust.
There should be a configuration variable for the lowest sized output created. If the change value is lower then add more inputs.

### PR DESCRIPTION
**Pull request by dooglus**
Fix #208.

### CODE REVIEW

**Comment by dooglus** [comment]
This isn't right - adding the dust threshold can put the amount we're trying to spend beyond the reach of the mix level we're trying to spend from. We need to run the mix level selection code again. I was testing this change with a high dust threshold, and saw:

    [2015/09/02 08:21:33] for mixdepth=2 amount=4862200 selected:
    [2015/09/02 08:21:33] [{'utxo': u'4f74d2667542988c1e5cf2535d503b185124c1bfdd4c717421e92c7c5dfd9f98:0',
      'value': 6807917}]
    [2015/09/02 08:21:33] change value=1945766 below dust threshold, finding new utxos
    [2015/09/02 08:21:33] get_utxos_by_mixdepth wallet.unspent = 
                          [...]
    [2015/09/02 08:21:33] dont have the required UTXOs to make a output above the dust threshold, quitting
    [2015/09/02 08:21:33] error<[...]> : unable to fill order constrained by dust avoidance
    [2015/09/02 08:21:33] >>privmsg nick=[...] cmd=error msg=unable to fill order constrained by dust avoidance
    [2015/09/02 08:21:33] cj peer error TODO handle

**Comment by chris-belcher** [comment]
What was your dust_threshold set as?

**Comment by dooglus** [comment]
I set:

    dust_threshold = 100000000

as a test to make sure it was working.

**Comment by dooglus** [comment]
5469b25 should fix the problem. It moves the mixdepth selection into a new function, and calls it again if the change is too small. It also now takes the fees into account when selecting the mixdepth and the uxto set.

**Comment by dooglus** [comment]
I ran my change and it appears to work. Here it is finding that mixlevel 1 is the best to fund a 0.33 BTC join, but then when it sees that I want 1 BTC change, it switches to mixlevel 0:

    [2015/09/02 12:17:58] <<privmsg nick=Hilakojof message=!fill 0 33734894 1c0009742046d6dae30286f8efc0309fbec2237dce76b68d248e7e318d7aa654
    [2015/09/02 12:17:58] new cjorder nick=Hilakojof oid=0 amount=33734894
    [2015/09/02 12:17:58] get_utxos_by_mixdepth wallet.unspent = {...}
    [2015/09/02 12:17:58] finding suitable mixdepth to spend amount=33734557
    [2015/09/02 12:17:58] using mixdepth=1
    [2015/09/02 12:17:58] get_utxos_by_mixdepth wallet.unspent = {...}
    [2015/09/02 12:17:58] for mixdepth=1 amount=33734557 selected:
    [2015/09/02 12:17:58] [{'utxo': u'fec6afc50c96cfe520829a7d4f3441d06cb84e4d5e9a4112def13c97857d0f73:1',  'value': 62187439}]
    [2015/09/02 12:17:58] change value=28452882 below dust threshold, finding new utxos
    [2015/09/02 12:17:58] get_utxos_by_mixdepth wallet.unspent = {...}
    [2015/09/02 12:17:58] finding suitable mixdepth to spend amount=133734557
    [2015/09/02 12:17:58] using mixdepth=0
    [2015/09/02 12:17:58] get_utxos_by_mixdepth wallet.unspent = {...}
    [2015/09/02 12:17:58] for mixdepth=0 amount=133734557 selected:
    [2015/09/02 12:17:58] [{'utxo': u'fec6afc50c96cfe520829a7d4f3441d06cb84e4d5e9a4112def13c97857d0f73:4',  'value': 632344598}]
    [2015/09/02 12:17:58] maker utxos = {u'fec6afc50c96cfe520829a7d4f3441d06cb84e4d5e9a4112def13c97857d0f73:4': {'address': u'1GPenofKdxnfWoGCAENNrVWphjzHFEzJik',
                                                                             'value': 632344598}}
    [2015/09/02 12:17:58] rpc: gettxout [u'fec6afc50c96cfe520829a7d4f3441d06cb84e4d5e9a4112def13c97857d0f73', 4, False]
    [2015/09/02 12:17:58] >>privmsg nick=Hilakojof cmd=pubkey msg=dc45bcfa0d61b490a64e9fb48dd3ccec38c996d6f0c7ca49c1c65161aad4c42f

**Comment by raedah** [comment]
This functionality is available in yield-generator-deluxe.py that is now in develop. The idea came from this pull request. Thanks. We probably dont need this in the basic yield generator. I suggest this be closed.

**Comment by adlai** [comment]
This PR must be closed because it's onto `master` instead of `develop`.

@dooglus If you wish to reopen this PR, please aim it onto the new branch.

**Pull request closed without merging**
