### PR TITLE
fix broken p2p test

### PR DESCRIPTION
**Pull request by chris-belcher**
https://github.com/JoinMarket-Org/joinmarket/pull/725#issuecomment-289233705

let's see what the automated testing says

edit: passed

### CODE REVIEW

**Comment by WyseNynja** [comment]
Nice. Once this is landed should I update my PRs?

**Comment by chris-belcher** [comment]
I think no because your PR didn't affect it and it passed all the other tests.

**Comment by AdamISZ** [comment]
Sure, no need to do anything @WyseNynja although i have a vague memory you can click the travis link and click a link top right to re-run the test. But don't worry either way.

**Comment by AdamISZ** [comment]
@chris-belcher so this passes? Anything holding it up?

**Comment by chris-belcher** [comment]
Nothing (except me not getting round to merging it)

**Pull request merged**
