### PR TITLE
Add link to "High level design"

### PR DESCRIPTION
**Pull request by meeDamian**
It took me a good while to find it, and was really helpful in making me understand fundamentals.

### CODE REVIEW

**Comment by chris-belcher** [comment]
ACK

**Comment by AdamISZ** [comment]
Also ACK but please base off develop, also I think it'd probably be better to phrase it as "go to (link to wiki) to get started, or for more in depth technical information,see (design doc)", something like that. Also worth noting that while the messaging protocol *.md file in the Docs repo has been updated for 0.2, then high level design has not as yet (not a huge deal, but would be nice for it to be updated).

**Comment by meeDamian** [comment]
Rebased to `develop` and wording changed as suggested. 

I think, even slightly outdated, design doc helps to understand the fundamental concepts a lot. And it can be updated any time later as well.

**Comment by AdamISZ** [comment]
Yes, thanks, will pop that in now.

**Pull request merged**
