### PR TITLE
Always load default config with initial values first, then load poten…

### PR DESCRIPTION
**Pull request by OverlordQ**
…tial config file afterwards

Fixed merge target from PR #404

### CODE REVIEW

**Comment by chris-belcher** [comment]
For those who were not able to read the relevant IRC conversation, the point of this patch is that if your joinmarket.cfg doesnt contain a certain field this code will now just load the default value instead of crashing complaining the value doesnt exist.

**Comment by chris-belcher** [comment]
Please target this PR at joinmarket:develop instead of joinmarket:master

**Comment by OverlordQ** [comment]
It is, it's just master on my repo.

**Comment by chris-belcher** [comment]
Derp. Thanks.

**Comment by AdamISZ** [comment]
utACK. Anyone tried it?

**Comment by AdamISZ** [comment]
Waited enough, merging.

**Pull request merged**
