### PR TITLE
Retry Blockr requests on network error

### PR DESCRIPTION
**Pull request by eduard6**
Retry Blockr requests on network error (DNS, timeout, etc)

Does not retry HTTP errors (to be conservative to avoid retrying invalid requests)

### CODE REVIEW

**Comment by AdamISZ** [comment]
Needs a rebase, should be trivial. It might be nice if someone tests this.

**Comment by eduard6** [comment]
Rebased

**Comment by AdamISZ** [comment]
Have we thought through what happens if a long sleep like this (up to 600 s) is occurring in a thread while other work continues?

**Comment by eduard6** [comment]
> Have we thought through what happens if a long sleep like this (up to 600 s) is occurring in a thread while other work continues?

I had not. I have not experienced any issues with it though even when it sleeps for that long. The time.sleep() call was based on the one from make_blockr_request() which has a maximum of 60 s. If 600 s seems too long I can change this pull request to 60 s too.

**Comment by eduard6** [comment]
Closing since blockr is obsolete now.

**Pull request closed without merging**
