### PR TITLE
fixup README installation instructions

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Comment by AlexCato** [comment]
This is not really a bug: if you downloaded the .tar.gz file from the first link given, the filename is correct as it is written right now.
If 2nd (direct) link was used, your correction would be the way to do it.

Since I assumed that the first link is used by most people, I used the extract command to fit that filename.

**Comment by instagibbs** [comment]
hm, perhaps I can change the other line to `wget https://github.com/JoinMarket-Org/joinmarket/archive/v0.2.2.tar.gz -O joinmarket-0.2.2.tar.gz`?

**Comment by AlexCato** [comment]
Since we're on the command line anyways at that point, that's imo an improvement over the status quo. Fine with me!

**Comment by chris-belcher** [comment]
Can you merge into the develop branch not the master branch

**Pull request closed without merging**
