### PR TITLE
issue #544: reject too many inputs from makers

### PR DESCRIPTION
**Pull request by AlexCato**
If there is more than 2 inputs from a maker, check if the maker paid a sufficient fee for the additional inputs. If not, reject him and choose another one.

Implicit joinmarket assumption: taker pays for ~1 input and 2 outputs of each maker. Some makers send very many inputs
and create a huge transaction, which crashes the tumbler/sendpayment scripts because the fee estimates are too
far off then. 

This issue sparked the idea: https://github.com/JoinMarket-Org/joinmarket/issues/544

### CODE REVIEW

**Comment by chris-belcher** [comment]
why 2 inputs ?

**Comment by AlexCato** [comment]
Magic number for which I have no clear justification.

For small joins, 1 would be sufficient.
For a big join, there's the problem that every maker's mixdepths will scatter a lot (thinkining of people offering 50 BTC and then a 48 BTC join comes along...)... so they either have to bump their tx fee contribution or are out of luck.
Thought of 2 as long-term viable middle ground. Probably can run merge_algorithm "gradual" with that and avoid getting too many UTXOs in the long term that way.

How would you handle it?

**Comment by AlexCato** [comment]
After our IRC-chat, we think a good way to improve this PR might be:

- try this approach 3-4 times. If no suitable makers are found, relax the conditions for maker selection
- do this by increasing the allowed amount of inputs per maker. Increase the allowed amount of inputs each iteration.
- add another magic number (max iterations) as stop criterion
- also needs to fix the #544 crash then and allow larger miner fees. Increase the allowed fees each iteration.
- let user confirm the increased miner fee

Aside from that, the sendpayment asks the user to confirm the cj fees before starting to initiate the coinjoin (but after selecting the makers). The miner fees should be displayed as well in the question to the user. Since those are not known at this point in time, the whole confirmation dialogue must be delayed until after the maker inputs are known. This will be another PR. Unsure when I find the time, hope this week.

**Comment by AlexCato** [comment]
Oh, didnt see this the first time i read it:

> I suppose there must be some cutoff, but I think with this the reality is that every single maker out there would be rejected.

I've tested the changes of course, both with smaller amounts (1 btc, 1.5btc, 2.5btc) and with a larger one (>20 btc). Worked like a charm with no problems. It's a small sample size though. It sometimes asked me to confirm 3 or 4 times when it restarted after a timeout, but always found a suitable match.

**Comment by AlexCato** [comment]
Will submit a new PR for this once it's done.

**Pull request closed without merging**
