### PR TITLE
New re-integration of secp256k1 via ludbb binding; no longer using

### PR DESCRIPTION
**Pull request by AdamISZ**
a local version but assuming the binding is installed already with
"pip install secp256k1". Does not yet include an updated form of the
donation code for custom nonces.
add mnemonic tests
Modification so that either secp256k1 or pybtc can be used;
secp256k1 python binding is detected automatically.

NOT YET READY TO MERGE.

Passes test suite currently both with and without secp256k1 module installed on the system.

Tests ongoing. Todo: re-add alternative code for donation tx. Test tumbler and modify if needed (I expect not). Apologies for re-formatting of create-unsigned-tx; will also need some testing there.

Will also need to add warning/info message if secp256k1 is not detected.

### CODE REVIEW

**Comment by chris-belcher** [comment]
I think this should be added after new release that pushes out all the fixes we've done in the last few months.

**Comment by AdamISZ** [comment]
@chris-belcher sounds reasonable; I've been thinking we should make a new release, too.

**Comment by AdamISZ** [comment]
Tumbler testing is passing with and without; with the new testing framework it'll be possible to add a variety of different setups, but in that case tests will take hours, so obviously won't be included in build tests. I'll probably do something along those lines later. Next up is the custom nonce issue. After that I'll do some tests of old and new bots together and then some live testing I guess.

**Comment by AdamISZ** [comment]
I've run some tests of this version of the donate code on both versions, it seems to operate fine - I checked that the receiving party can reconstruct the receiving key OK - not that there was much chance of it going wrong as it's essentially entirely unchanged.

The trick/hack is to simply import the necessary ECC functions *directly* from bitcoin.main in those 2 functions (see the diff), so that whether we are running with secp256k1 or not, it uses the old version of the code.

In related news, the owner of the secp256k1 repo is happy to pull the custom_nonce PR as long as I write a test for it. That update can happen whenever it's convenient.

The remaining work is to do more tests, in particular compatibility test of secp256k1 bots and non-secp256k1 bots together. I don't expect any trip ups at all here, as I dealt with that mess last November.

Final point, builds are passing, but coverage is not, for a specific reason: the addition of 3 new files (secp256k1_[main, deterministic, transaction].py) reduces the coverage, which counts as a failure to coveralls. Since builds already take 3-5 minutes in total including installation, I am not enamoured with the idea of adding a complete re-run of tests for both versions of the code. Suggestions on that point are welcome.

**Comment by AdamISZ** [comment]
Had forgotten to update the code for importing privkeys into wallet; this is now corrected, and so is the "meta-problem" that importprivkey was not tested.

**Pull request merged**
