### PR TITLE
refactoring for yieldgens

### PR DESCRIPTION
**Pull request by raedah**
These ran and completed a test transaction. Changes were for compatibility with latest refactor ( and yapf formatting).

### CODE REVIEW

**Comment by AdamISZ** [comment]
(Don't worry about the travis fail, I'll fix that).
This will need to be tested against tumbler-test for each of the new yield-generator types. See the comment to #349 .

**Comment by AdamISZ** [comment]
Running tumbler tests now.

The -mixdepth version is crashing, it seems because of this: https://github.com/JoinMarket-Org/joinmarket/pull/353/files#diff-3c58b00fab3804e7220db1ac4cdd652bR155

The mixdepth filtering is not checking against the 'amount' variable passed as argument to oid_to_order.

Second comment (can be put off): it seems weird to be re-defining the YieldGenerator *class* in these files separately, we should probably have a base yieldgenerator class and each of these can derive from it. But, no matter, we can look at that later.

Third comment, I don't understand why there's lots of reformatting code in this PR (e.g. irc.py, sendpayment.py). That should already be in @ghtdak's stuff? Or is it reformatting that he missed? (e.g. the print() statements in sendpayment).

**Comment by raedah** [comment]
1) the -mixdepth version crash, that code is exactly as it was in the new-yieldgen-algo branch. I haven't touched it. My next pull request was going to be a merging over the order filling code from -deluxe because of obvious problems with what is currently done in the -mixdepth version code. Mostly in regards to https://github.com/JoinMarket-Org/joinmarket/issues/156 , but ill look at this error too.

2) I have just been keeping with the way it was done. Ill ask you more about this.

3) The reformatting code is stuff that was missed, includes, prints, and I needed to get the tests to run. I also modified the tests to make it easier for my configuration.

**Comment by raedah** [comment]
I replaced most of the order filling code 'oid_to_order' in the yg-mixdepth.py code with the new code from the yg-deluxe.py.  This should fix the first issue @AdamISZ mentioned above, and well as fix the security vulnerability discussed over here https://github.com/JoinMarket-Org/joinmarket/issues/156#issuecomment-123750171

**Pull request merged**
